config/routes.rb
Rails.application.routes.draw do
  resources :idea_attachments

  resources :ideas do
    get :paging, on: :collection
  end

  resources :follows
  delete "unfollow" => "follows#destroy"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # get "profile" => "users#show"
  # get "profile"   => "users#show"
  get "searchresult" => "users#searchresult"
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :reaches

  resources :comments

  #like
  post "toggle_like" => "likes#toggle"


  #home page
  root "home#index"
  get "text" => "home#text"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :participates
end

app/models/idea_attachment.rb
class IdeaAttachment < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :idea
end

app/controllers/idea_attachments_controller.rb
class IdeaAttachmentsController < ApplicationController
  before_action :set_idea_attachment, only: [:show, :edit, :update, :destroy]

  # GET /idea_attachments
  # GET /idea_attachments.json
  def index
    @idea_attachments = IdeaAttachment.all
  end

  # GET /idea_attachments/1
  # GET /idea_attachments/1.json
  def show
  end

  # GET /idea_attachments/new
  def new
    @idea_attachment = IdeaAttachment.new
  end

  # GET /idea_attachments/1/edit
  def edit
  end

  # POST /idea_attachments
  # POST /idea_attachments.json
  def create
    @idea_attachment = IdeaAttachment.new(idea_attachment_params)

    respond_to do |format|
      if @idea_attachment.save
        format.html { redirect_to @idea_attachment, notice: 'Idea attachment was successfully created.' }
        format.json { render :show, status: :created, location: @idea_attachment }
      else
        format.html { render :new }
        format.json { render json: @idea_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /idea_attachments/1
  # PATCH/PUT /idea_attachments/1.json
  def update
    respond_to do |format|
      if @idea_attachment.update(idea_attachment_params)
        format.html { redirect_to @idea_attachment, notice: 'Idea attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea_attachment }
      else
        format.html { render :edit }
        format.json { render json: @idea_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /idea_attachments/1
  # DELETE /idea_attachments/1.json
  def destroy
    @idea_attachment.destroy
    respond_to do |format|
      format.html { redirect_to idea_attachments_url, notice: 'Idea attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea_attachment
      @idea_attachment = IdeaAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_attachment_params
      params.require(:idea_attachment).permit(:idea_id, :photo)
    end
end

app/helpers/idea_attachments_helper.rb
module IdeaAttachmentsHelper
end

app/views/idea_attachments/_form.html.erb
<%= form_with(model: idea_attachment, local: true) do |form| %>
  <% if idea_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea_attachment.errors.count, "error") %> prohibited this idea_attachment from being saved:</h2>

      <ul>
      <% idea_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idea_id %>
    <%= form.text_field :idea_id, id: :idea_attachment_idea_id %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :idea_attachment_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/idea_attachments/edit.html.erb
<h1>Editing Idea Attachment</h1>

<%= render 'form', idea_attachment: @idea_attachment %>

<%= link_to 'Show', @idea_attachment %> |
<%= link_to 'Back', idea_attachments_path %>

app/views/idea_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Idea Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Idea</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @idea_attachments.each do |idea_attachment| %>
      <tr>
        <td><%= idea_attachment.idea %></td>
        <td><%= idea_attachment.photo %></td>
        <td><%= link_to 'Show', idea_attachment %></td>
        <td><%= link_to 'Edit', edit_idea_attachment_path(idea_attachment) %></td>
        <td><%= link_to 'Destroy', idea_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea Attachment', new_idea_attachment_path %>

app/views/idea_attachments/new.html.erb
<h1>New Idea Attachment</h1>

<%= render 'form', idea_attachment: @idea_attachment %>

<%= link_to 'Back', idea_attachments_path %>

app/views/idea_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idea:</strong>
  <%= @idea_attachment.idea %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @idea_attachment.photo %>
</p>

<%= link_to 'Edit', edit_idea_attachment_path(@idea_attachment) %> |
<%= link_to 'Back', idea_attachments_path %>