config/routes.rb
Rails.application.routes.draw do
  resources :idea_attachments

  resources :ideas do
    get :paging, on: :collection
  end

  resources :follows
  delete "unfollow" => "follows#destroy"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # get "profile" => "users#show"
  # get "profile"   => "users#show"
  get "searchresult" => "users#searchresult"
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :reaches

  resources :comments

  #like
  post "toggle_like" => "likes#toggle"


  #home page
  root "home#index"
  get "text" => "home#text"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :participates
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user, class_name: "User"
  has_many :idea_attachments
  accepts_nested_attributes_for :idea_attachments
  belongs_to :category
  belongs_to :type
  has_many :participates, dependent: :destroy
  has_many :joiners, through: :participates, source: "joiner"
  has_many :reaches
  has_and_belongs_to_many :hashtags
  has_many :likes, as: :item
  has_many :comments, dependent: :destroy
  validates :body,:title, presence: true
  after_create do
    puts "after created!"
    idea = Idea.find_by(id: self.id)
    listhashtags = self.body.scan(/#\w+/)
    listhashtags.uniq.map do |ht|
      hashtag = Hashtag.find_or_create_by(name: ht.downcase.delete('#'))
      idea.hashtags << hashtag
    end
  end

  before_update do
    idea = Idea.find_by(id: self.id)
    idea.hashtags.clear
    listhashtags.uniq.map do |ht|
      hashtag = Hashtag.find_or_create_by(name: ht.downcase.delete('#'))
      idea.hashtags << hashtag
    end
  end
  def idea_updated_at
    updated_at|| Time.new()
  end
  def self.generate_ideas(n = 5, user = nil)

    user ||= User.last
    n.times do
        a=''
        b = nil
        loop do
          b = Behance::Client.new(access_token: ENV.fetch('API_BEHANCE_KEY')).collections.first["latest_projects"].first["covers"]
          if b
            a = b["404"]
          end
          break if b !=nil
        end
        hashtag_idea = '#'+Faker::Job.field
        body_idea = ' '+ Faker::Hobbit.quote
        idea = Idea.create!(
        title: Faker::Cat.breed,
        body: hashtag_idea +  body_idea,
        need: Faker::Job.title,
        image_url: a,
        category_id: rand(1..5),
        type_id: rand(1..3),
        user: User.random_user,
      )
       rand(8).times do
         idea.comments.create(
           body: Faker::Hacker.say_something_smart,
           user: User.random_user,
         )
       end
       rand(30).times do
         idea.likes.create(
           user: User.random_user,
         )
       end
       rand(30).times do
         idea.participates.create(
           skills: "abc", details: "xyz", joiner: User.random_user
           )
       end
    end
  end

  def self.find_ideas_by_hashtag(hashtag)
    hashtag = Hashtag.find_by(name: hashtag)
    if hashtag!=nil
      return hashtag.ideas
    end
  end

  def image_url_or_photo
    if idea_attachments.first
      return idea_attachments.first.photo
    else
      image_url.presence||  "idea.jpg"
    end
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @idea = Idea.new
    @idea_attachment = @idea.idea_attachments.build
    @participate = Participate.new
    if params[:sort_by] =="view"
      @ideas = Idea.joins(:reaches).select("ideas.*, count(reaches.id) as reach_count").group("ideas.id").order("reach_count DESC").page(1).per(2)
    elsif params[:sort_by] =="comment"
      @ideas =  Idea.joins(:comments).select("ideas.*,count(comments.id) as comment_count").group("ideas.id").order("comment_count DESC").page(1).per(2)
    elsif params[:sort_by] =="join"
      @ideas =  Idea.joins(:participates).select("ideas.*,count(participates.id) as participate_count").group("ideas.id").order("participate_count DESC").page(1).per(2)
    else
      @ideas =  Idea.joins(:likes).select("ideas.*,count(likes.id) as like_count").group("ideas.id").order("like_count DESC").page(1).per(2)
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @comment = Comment.new
    if current_user.reaches.where(idea_id: @idea.id).count == 0
      reach = current_user.reaches.build idea: @idea
      if reach.save
      else
        flash[:error] = "Error: #{reach.errors.full_messages.to_sentence}"
      end
    end
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
    @idea_attachment = @idea.idea_attachments.build
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = current_user.ideas.build idea_params
    if @idea.save
      if params[:idea_attachments]
        params[:idea_attachments][:photo].each do |a|
          @idea_attachment = @idea.idea_attachments.create!(photo: a)
        end
      end
      current_user.reaches.create idea: @idea
      respond_to do |f|
        f.html{ redirect_back(fallback_location: root_path) }
        f.js { render 'idea' }
      end

    else
      flash[:error] = "Error: #{@idea.errors.full_messages.to_sentence}"
      # format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
      # format.json { render :show, status: :created, location: @idea }
      # format.html { render :new }
      # format.json { render json: @idea.errors, status: :unprocessable_entity }
    end

  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def paging
    @participate = Participate.new
    params[:per] ||= 2
    @ideas = Idea.order("updated_at DESC").page(params[:page]).per(params[:per])
    render partial: "idea", collection: @ideas, layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title,:need, :body,:category_id,:type_id,idea_attachments_attributes: [:id, :idea_id, :photo])
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
  def display_likers(idea)
    idea.likes.map{|like| like.name_or_email}.to_sentence
  end
end

app/views/ideas/_idea.html.erb
<div class="card-show-idea" id="<%= dom_id idea %>">
  <div class="card js-idea <%="#{'js-idea-reach' unless current_user.reaching?(idea)}"%>" id="<%= dom_id idea %>">
    <div class="card-header">
      <div class="card-header-title wrapper" style="padding-bottom:1px">
        <%= link_to "#{idea.title}", idea_path(idea.id)  %>
      </div>
    </div>
    <div class="card-content"  style="min-height:469px;">
      <div class="content" >
        <div class="body" style="border: 1px solid #bbbbbb;min-height:200px;border-radius: 10px; padding:20px">
          <%= simple_format idea.body %>
        </div>
      </div>
      <div class="content">
        <strong> Category: </strong>
        <span class="js-idea-category"> <%= idea.category.name %> </span>
      </div>
      <div class="content">
       <strong> In need: </strong>
        <span class="js-idea-need"> <%= idea.need %> </span>
      </div>
      <div class="content">
        <strong><%= idea.joiners.count %></strong>
        Wanna join this idea
      </div>
      <div class="content">
        <nav class="level">
          <div class="level-left">
          </div>
          <div class="level-right">
            <div class="level-item" style="margin-right:50px">
              <div class="">
                <div class="control new-join" style="vertical-align: middle;">
                  <% unless idea.user==current_user|| current_user.joined_ideas.include?(idea) %>
                    <a class="button is-primary modal-join js-modal-join-idea" data-target="modal" >Join</a>
                  <% end %>
                </div>
              </div>
            <div>
          </div>
        </nav>
      </div>
    </div>
    <div class="card-image">
      <figure class="image image-idea is-4by3">
          <%= image_tag(idea.image_url_or_photo, class: "card-image ") %>
      </figure>
    </div>
    <footer>
      <nav class="level" style="margin-right:10px">
        <div class="level-left">
        </div>
        <div class="level-right">
          <div class="level-item js-reach-num" >
            <%= icon("eye-slash", "#{idea.reaches.count}")  %>
          </div>
          <div class="level-item js-cmt-num">
            <%= icon("comments", "#{idea.comments.count}")%>
          </div>
          <div class="level-item">
            <%= link_to icon("heart-o","#{idea.likes.count}"),toggle_like_path(idea_id: idea.id), class: "js-like-button #{'is-liked' if current_user.liking?(idea)}", method: "post", remote: true %>
          </div>
        </div>
      </nav>
    </footer>
  </div>
  <div class="media name-hover">
    <div class="media-left">
      <figure class="image image-round is-64x64">
        <%= image_tag(idea.user.image_url_or_default, alt: "image") %>
      </figure>
    </div>
    <div class="media-content">
      <p class="title is-4">
        <%= link_to idea.user.name_or_email,user_path(idea.user.id)  %>
      </p>
      <p class="subtitle is-6">
        <small><%= time_ago_in_words idea.idea_updated_at %> ago</small>
      </p>
    </div>
    <%= render "participates/new", idea: idea %>
  </div>
</div>

app/views/ideas/_ideapf.html.erb
<div class="card-show-idea" id="<%= dom_id idea %>" style="min-width:620px;min-height:620px">
  <div class="card js-idea <%="#{'js-idea-reach' unless current_user.reaching?(idea)}"%>" id="<%= dom_id idea %>">
    <div class="card-header">
      <div class="card-header-title wrapper" style="padding-bottom:1px">
        <%= link_to "#{idea.title}", idea_path(idea.id)  %>
      </div>
    </div>
    <div class="card-content"  style="min-height:469px;">
      <div class="content" >
        <div class="body" style="border: 1px solid #bbbbbb;min-height:200px;border-radius: 10px; padding:20px">
          <%= simple_format idea.body %>
        </div>
      </div>
      <div class="content">
        <strong> Category: </strong>
        <span class="js-idea-category"> <%= idea.category.name %> </span>
      </div>
      <div class="content">
       <strong> In need: </strong>
        <span class="js-idea-need"> <%= idea.need %> </span>
      </div>
      <div class="content">
        <strong><%= idea.joiners.count %></strong>
        want to join this idea
      </div>
      <div class="content">
        <nav class="level">
          <div class="level-left">
          </div>
          <div class="level-right">
            <div class="level-item" style="margin-right:50px">
              <div class="">
                <div class="control new-join" style="vertical-align: middle;">
                  <% unless idea.user==current_user|| current_user.joined_ideas.include?(idea) %>
                    <a class="button is-primary modal-join js-modal-join-idea" data-target="modal" >Join</a>
                  <% end %>
                </div>
              </div>
            <div>
          </div>
        </nav>
      </div>
    </div>
    <div class="card-image">
      <figure class="image image-idea is-4by3">
          <%= image_tag(idea.image_url_or_photo, class: "card-image ") %>
      </figure>
    </div>
    <footer>
      <nav class="level" style="margin-right:10px">
        <div class="level-left">
        </div>
        <div class="level-right">
          <div class="level-item js-reach-num" >
            <%= icon("eye-slash", "#{idea.reaches.count}")  %>
          </div>
          <div class="level-item js-cmt-num">
            <%= icon("comments", "#{idea.comments.count}")%>
          </div>
          <div class="level-item">
            <%= link_to icon("heart-o","#{idea.likes.count}"),toggle_like_path(idea_id: idea.id), class: "js-like-button #{'is-liked' if current_user.liking?(idea)}", method: "post", remote: true %>
          </div>
        </div>
      </nav>
    </footer>
  </div>
  <%= render "participates/new", idea: idea %>
</div>

app/views/ideas/_new.html.erb
<div class="modal js-modal-new-idea">
  <div class="modal-background js-modal-background-new-idea"></div>

  <div class="modal-content content-new">
    <h1 style="text-align: center; padding-top:10px; background-color:#343d46;color:white ">More Ideas more mellons</h1>
    <%= form_for @idea, html: { multipart: true } , remote: true do |f| %>
      <div class="control" style="margin:30px; margin-top:1px">
        <div class="wrapper" >
          <figure class="image image-round is-96x96">
            <%= image_tag(current_user.image_url_or_default, alt: "image") %>
          </figure>
        </div>
        <div class="field">
          <div class="control">
            <div class="select">
              <%= f.select :type_id,options_from_collection_for_select(Type.all, :id, :name) %>
            </div>
          </div>
        </div>
        <label class="label" style="margin-left:10px"> Title: </label>
        <%= f.text_field :title, class: "form-control input title-input"%>
        <label class="label" style="margin:10px"> Something about your new idea: </label>
        <%= f.text_area :body, class: "form-control textarea body-textarea", placeholder: "We love your Idea..." %>
        <div class="control" style="margin-top:20px">
          <div class="level">
            <div class="level-left">
              <label class="label" style="margin-left:10px"> Category: </label>
            </div>
            <div class="level-left" style="margin-right:180px;">
              <div class="field">
                <div class="control">
                  <div class="select">
                    <%= f.select :category_id,options_from_collection_for_select(Category.all, :id, :name) %>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </div>
        <label class="label" style="margin-left:10px"> In need: </label>
        <%= f.text_field :need, class: "form-control input need-input"%>
        <div class="control", style="padding:5px; margin-top:20px">
          <div class="level">
            <div class="level-left">
              <div class="file">
                <label class="file-label ">
                  <%= f.fields_for :idea_attachments do |p| %>
                    <%= p.file_field :photo,:multiple => true, name: "idea_attachments[photo][]", class: "file-input" %>
                    <span class="file-cta" style="margin-left:30px">
                      <%= icon("camera-retro", "Photo") %>
                    </span>
                  <% end %>
                </label>
              </div>
            </div>
            <div class="level-right">
              <%= f.submit "Post", class: "button is-primary js-post", style: "margin-right:30px" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <button class="modal-close js-modal-close-new-idea is-large" aria-label="close"></button>
</div>

app/views/ideas/_show.html.erb
<div class="content">
  <nav class="parent">
    <h1>Hello Sunny Vo</h1>
  </nav>
  <div class="columns child is-multiline is-mobile">
    <div class="column is-two-thirds">
      <div class="media name-hover">
        <div class="media-left">
          <figure class="image image-round is-64x64">
            <%= image_tag(idea.user.image_url_or_default, alt: "image") %>
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-4">
            <%= link_to idea.user.name_or_email,""  %>
          </p>
          <p class="subtitle is-6">
            <small><%= time_ago_in_words idea.idea_updated_at %> ago</small>
          </p>
        </div>
      </div>
      <div class="card-footer footer-like">
        <%= display_likers(@idea) %>
      </div>
      <div class="media">
        <div class="media-left">
          <p class="image is-32x32">
            <%= image_tag(current_user.image_url_or_default, class: "card-image") %>
          </p>
        </div>
        <div class="media-content new-comment", id="<%=dom_id idea %>">
          <%= render "comments/new", idea: @idea %>
        </div>
      </div>
      <div class="comments-list" id="<%=dom_id @idea %>">
        <% @idea.comments.each do |cmt| %>
          <%= render "comments/comment", cmt: cmt %>
        <% end %>
      </div>
    </div>
    <div class="column">
      second column
    </div>
  </div>
</div>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/idea.js.erb
<% if @idea.idea_attachments.first %>
  $($(".card-show-idea")[0]).find(".image-idea img").attr("src","<%= @idea.idea_attachments.last.photo.url %>")
<% end %>
$(".js-modal-new-idea").find(".body-textarea").val("");
$(".js-modal-new-idea").find(".title-input").val("");
$(".js-modal-new-idea").find(".need-input").val("");
$(".js-modal-new-idea").find("#idea_category_id").val("1");
$(".js-modal-new-idea").find("#idea_type_id").val("1");
$(".js-modal-new-idea").find(".file-input").val("");

app/views/ideas/index.html.erb
<div class="content">
  <nav class="parent" style="">
      <div class="media name-hover">
        <div class="media-left">
          <figure class="image image-round is-96x96">
             <%= image_tag "mellon2.jpg" %>
          </figure>
        </div>
        <div class="media-content">
          <h1 class="title is-4" style="">
            Welcome to Mellon Generation
          </h1>
        </div>
      </div>
  </nav>
  <div class="columns  is-multiline is-mobile ">
    <div class="column is-2" style="background-color:lightgray;">
    </div>
    <div class="column child is-8" >
      <div class="control wrapper">
        <span class="" style="">
          <%= link_to "Joiners", ideas_path(:sort_by => "join"), class: "button is-primary  is-large filter-btn" %>
        </span>
        <span class="" style="">
          <%= link_to "Views", ideas_path(:sort_by => "view"), class: "button is-primary  is-large filter-btn" %>
        </span>
        <span class="" style="">
          <%= link_to "Loves", ideas_path(:sort_by => "love"), class: "button is-primary  is-large filter-btn" %>
        </span>
        <span class="" style="">
          <%= link_to "Comments", ideas_path(:sort_by => "comment"), class: "button is-primary  is-large filter-btn" %>
        </span>
      </div>
      <div class="ideas-list">
        <% @ideas.each do |idea| %>
          <%= render "ideas/idea", idea: idea %>
        <% end %>
      </div>
      <div class="pagination" data-pagination-endpoint="<%= paging_ideas_path %>" data-pagination-pages="<%= @ideas.total_pages %>">
        <i class="fa fa-spinner fa-pulse fa-3x fa-fw" style="margin: auto"></i>
      </div>
    </div>
    <div class="column" style="background-color:lightgray;">

    </div>
  </div>
</div>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="content">
  <nav class="parent">
  </nav>
  <div class="columns child is-multiline is-mobile" style="background-color:lightgray;">
    <div class="column is-two-thirds" style="padding:40px;">
      <div class="media name-hover" style="margin-bottom:20px;">
        <div class="media-left">
          <figure class="image image-round is-96x96">
            <%= image_tag(@idea.user.image_url_or_default, alt: "image")%>
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-4" style="padding-top:20px;">
            <%= link_to @idea.title %>
          </p>
          <p class="subtitle is-6">
            <small> by <strong><%= link_to @idea.user.name_or_email,user_path(@idea.user.id)  %> </strong>  <%=  time_ago_in_words @idea.idea_updated_at %> ago</small>
          </p>
        </div>
      </div>

      <div class="">
        <div class="idea-info" style="padding:20px">
        <%= @idea.body %>
        </div>
        <div style="margin-top:30px">
            <%= image_tag(@idea.image_url_or_photo, class: "",style: "height:300px;width:400px") %>
        </div>
      </div>
      <div class="fb-share-button" data-href="http://localhost:3000/ideas/<%= @idea.id %>" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Share on FB</a></div>
      <lable> <h3 style="margin-top:20px;"> Add a new comment <h3> </lable>
      <div class="new-comment">
        <%= render "comments/new", idea: @idea %>
      </div>
      <div class="comments-list">
        <% @idea.comments.each do |cmt| %>
          <%= render "comments/comment", cmt: cmt %>
        <% end %>
      </div>
    </div>
    <div class="column" style="padding-top:170px">
      <div class="level" id="<%=dom_id @idea%>">
        <div class="level-left">
          <div class="level-item">
           <%= link_to icon("heart-o","#{@idea.likes.count}"),toggle_like_path(idea_id: @idea.id), class: "js-like-button #{'is-liked' if current_user.liking?(@idea)}", method: "post", remote: true %>
          </div>
          <div class="level-item">
          Likes
          </div>
        </div>
        <div class"level-right">
        </div>
      </div>
      <div class="control" style=" margin-top:200px">
        <div>
          <p style="margin-top:30px">
            <strong> Member(<%= @idea.joiners.count %>): </strong>
            <% @idea.joiners.limit(4).each  do |joiner| %>
              <p class="js-num-member" style="margin-left:20px">
                <%= joiner.name %>
              </p>
            <% end %>
          </p>
          <p>
            <strong> In need: </strong>
            <p class="" style="margin-left:20px"><%= @idea.need %></p>
          </p>
          <p style="margin-top:30px">
            <strong> Demo: </strong>
            <a hef="https://www.youtube.com/watch?v=io9iEy00vQo" class=""> Youtube</a>
          </p>

          <p style="margin-top:30px">
            <strong> TODO lists: </strong>
            <a hef="https://trello.com/b/18A0VGdG/br1-final-projects" class=""> Trello</a>
          </p>
          <p style="margin-top:50px">
            <strong> Hash tag: </strong>
            <p>
              <% @idea.hashtags.each  do |hash| %>
                <span class="js-num-member" style="margin-left:20px">
                  <%= hash.name %>
                </span>
              <% end %>
            </p>
          </p>
        </div>
    </div>
  </div>
  <div class="fb-comments" data-href="http://localhost:3000/ideas/<%= @idea.id %>" data-numposts="5"></div>
</div>