config/routes.rb
Rails.application.routes.draw do
  resources :idea_attachments

  resources :ideas do
    get :paging, on: :collection
  end

  resources :follows
  delete "unfollow" => "follows#destroy"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # get "profile" => "users#show"
  # get "profile"   => "users#show"
  get "searchresult" => "users#searchresult"
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :reaches

  resources :comments

  #like
  post "toggle_like" => "likes#toggle"


  #home page
  root "home#index"
  get "text" => "home#text"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :participates
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:facebook]
  has_many :ideas, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :follows, dependent: :destroy
  has_many :followers, through: :follows
  has_many :participates
  has_many :likes, dependent: :destroy
  # has_many :joined_ideas, through: :participates, source: 'idea'
  has_many :joined_ideas, through: :participates, source: 'joined_idea'
  has_many :reaches
  has_many :comments, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image_url = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def image_url_or_default
    avatar.url|| image_url.presence || "idea.jpg"
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.generate_users(n = 5, gender = "female")
    url = "https://randomuser.me/api?results=#{n}&gender=#{gender}"
    body = HTTP.get(url).parse
    body["results"].each do |person|
      hash = {}
      hash[:name] = person["name"]["first"] + " " + person["name"]["last"]
      hash[:email] = person["email"]
      o = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
      string = (0...10).map { o[rand(o.length)] }.join
      hash[:password] = string
      hash[:image_url] = person["picture"]["large"]
      user = User.create! hash
    end


  end

  def self.num_followedby(user)
    Follow.where(follower: user).count
  end

  def self.num_ideas(user)
    user.ideas.count
  end

  def self.num_joined_ideas(user)
    user.joined_ideas.count
  end

  def is_followed?(user)
    followers.include?(user)
  end

  def name_or_email
    name || email
  end

  def liking?(item)
    likes.where(item: item).exists?
  end

  def reaching?(idea)
    reaches.where(idea: idea).exists?
  end


  def toggle_like!(item)
    if like = likes.where(item: item).first
      like.destroy
    else
      likes.where(item: item).create!
    end
  end

  def self.autocomplete(name)
    User.where("name ILIKE ? ", "%#{name}%")
  end
  def self.random_user
    User.offset(rand User.count).first
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end
  # def callback
  #   if user = User.from_omniauth(request.env["omniauth.auth"])
  #     login(user)
  #     redirect_to root_path
  #     # redirect_to root_path, flash: {success: "Logged in!"}
  #     # log in user here
  #   else
  #     redirect_to root_path
  #     # don't log user in
  #   end
  # end

  # #DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def searchresult
    @participate = Participate.new
    if params[:search]
      @users = User.autocomplete(params[:search])
      @ideas = Idea.find_ideas_by_hashtag(params[:search])
    else
      @users = User.all.limit(5)
    end
  end

  # def profile
  #   @ideas = [Idea.find(Reach.group(:idea_id).count.max_by{ |key, value| value}[0])]
  # end

  def search

    @users = User.autocomplete(params[:name])
    @ideas = Idea.find_ideas_by_hashtag(params[:name])
    puts "text:"
    puts @ideas
    respond_to do |format|
      format.json
    end
  end

  def show
    @idea = Idea.new
    @idea_attachment = @idea.idea_attachments.build
    @participate = Participate.new
    @user = User.find_by(id: params[:id] )
    @ideas = @user.ideas.order("updated_at DESC")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_cardamination.html.erb
 <aside class="profile-card css-profile" id="<%=dom_id user%>">
  <header>
    <%= link_to user_path(id: user) do %>
      <%= image_tag user.image_url_or_default%>
    <% end %>
    <h1 class="title is-4"><%= user.name %></h1>
    <h2 class="subtitle is-6"><%= user.email %></h2>
  </header>
  <div class="profile-bio">
  <footer class="card-footer">
      <a class="card-footer-item js-unfollow <%= current_user.is_followed?(user) ? " " : "hidden" %>">
        <%= form_for user, url: unfollow_path(user_id: user.id), method: :delete, remote: true do |f| %>
          <button class="button is-danger add-remove is-inverted"><%= icon("user-times", "Unfollow") %></button>
        <% end %>
      </a>
      <a class="card-footer-item js-follow <%= current_user.is_followed?(user) ? "hidden" : " " %>">
        <%= form_for current_user.follows.build(follower: user), remote: true do |f| %>
          <%= f.hidden_field :follower_id %>
          <button class="button is-primary  is-inverted "><%= icon("user-plus", "Follow") %></button>
        <% end %>
      </a>
  </footer>
  <footer>
    <nav class="level" style="margin-right:10px">
      <div class="level-left">
      </div>
      <div class="level-right">
        <div class="level-item">
          <%= icon("paw", "#{User.num_followedby(user)}") %>
        </div>
        <div class="level-item">
          <%= icon("lightbulb-o", "#{User.num_ideas(user)}") %>
        </div>
        <div class="level-item">
          <%= icon("plus-circle","#{User.num_joined_ideas(user)}") %>
        </div>
      </div>
    </nav>
  </footer>
</aside>

app/views/users/_cardprofile.html.erb
<div class="container-card" id="<%=dom_id user%>">
  <div class="card">
    <div class="card-title">
      <div class="icon-idea">
        <a> <%= icon("lightbulb-o","") %> </a>
      </div>
      <div class="card-image">
        <figure class="image is-64x64">
          <%= image_tag(user.image_url_or_default, alt: "image") %>
        </figure>
      </div>
    </div>
    <div class="card-content">
      <div class="content">
        <h5>
          <%= user.name_or_email %>
        </h5>
        <p> Followed by: <%= User.num_followedby(user)%></p>
      </div>
      <a class="card-footer-item js-unfollow <%= current_user.is_followed?(user) ? " " : "hidden" %>">
        <%= form_for user, url: unfollow_path(user_id: user.id), method: :delete, remote: true do |f| %>
          <button class="button is-danger add-remove is-inverted"><%= icon("user-times", "Unfollow") %></button>
        <% end %>
      </a>
      <a class="card-footer-item js-follow <%= current_user.is_followed?(user) ? "hidden" : " " %>">
        <%= form_for current_user.follows.build(follower: user), remote: true do |f| %>
          <%= f.hidden_field :follower_id %>
          <button class="button is-primary  is-inverted "><%= icon("user-plus", "Follow") %></button>
        <% end %>
      </a>
    </div>
    <footer class="card-footer">
      <nav class="level" style="margin-right:10px">
        <div class="level-left">
        </div>
        <div class="level-right">
          <div class="level-item">
            <%= icon("paw", "122") %>
          </div>
          <div class="level-item">
            <%= icon("lightbulb-o", "2") %>
          </div>
          <div class="level-item">
            <%= icon("plus-circle","102") %>
          </div>
        </div>
      </nav>
    </footer>
  </div>
</div>

app/views/users/_user.html.erb
 <aside class="profile-card friend", id="<%= dom_id another_user %>">
  <header>
    <%= link_to profile_path(id: user) do %>
      <%= image_tag user.image_url_or_default%>
    <% end %>
    <h1 class="title is-4"><%= user.name %></h1>
    <h2 class="subtitle is-6"><%= user.email %></h2>
  </header>
  <div class="profile-bio">
    <p> Followed by: <%= User.num_followedby(user)%></p>
  <footer class="card-footer">
          <a class="card-footer-item js-remove <%= current_user.is_followed?(user) ? " " : "hidden" %>">
            <%= form_for user, url: remove_friend_path(user_id: user.id), method: :delete, remote: true do |f| %>
              <button class="button is-danger add-remove is-inverted"><%= icon("user-times", "Remove Friend") %></button>
            <% end %>
          </a>
          <a class="card-footer-item js-add <%= current_user.is_followed?(user) ? "hidden" : " " %>">
            <%= form_for current_user.follows.build(friend: another_user), remote: true do |f| %>
              <%= f.hidden_field :friend_id %>
              <button class="button is-primary  is-inverted "><%= icon("user-plus", "Add Friend") %></button>
            <% end %>
          </a>
  </footer>
</aside>

app/views/users/profiles.html.erb
<div class="content">
  <nav class="parent" style="">
      <div class="media name-hover">
        <div class="media-left">
          <figure class="image image-round is-96x96">
             <%= image_tag "mellon2.jpg" %>
          </figure>
        </div>
        <div class="media-content">
          <h1 class="title is-4" style="">
            Welcome to Mellon Generation
          </h1>
        </div>
      </div>
  </nav>
  <div class="columns  is-multiline is-mobile ">
    <div class="column is-2" style="background-color:lightgray;">
    </div>
    <div class="column child is-8">
      <div class="columns is-multiline friends-list" style="background-color:#87CEFA;">
        <% @users.except(current_user).each do |stranger| %>
          <%= render "cardamination", user: stranger  %>
        <% end %>
      </div>
    </div>
    <div class="column" style="background-color:lightgray;">

    </div>
  </div>
</div>

app/views/users/searchresult.html.erb
<div class="content">
  <nav class="parent" style="">
      <div class="media name-hover">
        <div class="media-left">
          <figure class="image image-round is-96x96">
             <%= image_tag "mellon2.jpg" %>
          </figure>
        </div>
        <div class="media-content">
          <h1 class="title is-4" style="">
            Welcome to Mellon Generation
          </h1>
        </div>
      </div>
  </nav>
  <div class="columns  is-multiline is-mobile ">
    <div class="column is-2" style="background-color:lightgray;">
    </div>
    <div class="column child is-8">
      <div class="columns is-multiline friends-list" style="background-color:#87CEFA;">
        <% @users.except(current_user).each do |stranger| %>
          <%= render "cardamination", user: stranger  %>
        <% end %>
      </div>
      <h1> Ideas: </h1>
      <div class="columns is-multiline friends-list" style="background-color:#87CEFA;">
        <% if @ideas %>
          <% @ideas.each do |idea| %>
            <%= render "ideas/ideapf", idea: idea  %>
          <% end %>
        <% else %>
          <p>
            No ideas to show
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="content">
  <nav class="parent" style="">
      <div class="media name-hover">
        <div class="media-left">
          <figure class="image image-round is-96x96">
             <%= image_tag "mellon2.jpg" %>
          </figure>
        </div>
        <div class="media-content">
          <h1 class="title is-4" style="">
            Welcome to Mellon Generation
          </h1>
        </div>
      </div>
  </nav>
  <div class="media name-hover" style="margin-bottom:20px;">
    <div class="media-left">
      <figure class="image image-round is-96x96">
        <%= image_tag(@user.image_url_or_default, alt: "image")%>
      </figure>
    </div>
    <div class="media-content">
      <p class="title is-4" style="padding-top:20px;">
        <%= link_to @user.name_or_email %>
      </p>
    </div>
  </div>
  <div class="columns  is-multiline is-mobile ">
    <div class="column is-2" style="background-color:lightgray;">
    </div>
    <div class="column child is-8">
      <div class="columns is-multiline friends-list" style="background-color:#87CEFA;">
        <% @ideas.each do |idea| %>
          <%= render "ideas/ideapf", idea: idea  %>
        <% end %>
      </div>
    </div>
    <div class="column" style="background-color:lightgray;">

    </div>
  </div>
</div>