config/routes.rb
Rails.application.routes.draw do
  resources :idea_attachments

  resources :ideas do
    get :paging, on: :collection
  end

  resources :follows
  delete "unfollow" => "follows#destroy"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # get "profile" => "users#show"
  # get "profile"   => "users#show"
  get "searchresult" => "users#searchresult"
  resources :users do
    collection do
      get 'search'
    end
  end
  resources :reaches

  resources :comments

  #like
  post "toggle_like" => "likes#toggle"


  #home page
  root "home#index"
  get "text" => "home#text"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :participates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ideas
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  has_many :likes, as: :item
  validates :body, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :follower, class_name: "User"
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  has_and_belongs_to_many :ideas
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user, class_name: "User"
  has_many :idea_attachments
  accepts_nested_attributes_for :idea_attachments
  belongs_to :category
  belongs_to :type
  has_many :participates, dependent: :destroy
  has_many :joiners, through: :participates, source: "joiner"
  has_many :reaches
  has_and_belongs_to_many :hashtags
  has_many :likes, as: :item
  has_many :comments, dependent: :destroy
  validates :body,:title, presence: true
  after_create do
    puts "after created!"
    idea = Idea.find_by(id: self.id)
    listhashtags = self.body.scan(/#\w+/)
    listhashtags.uniq.map do |ht|
      hashtag = Hashtag.find_or_create_by(name: ht.downcase.delete('#'))
      idea.hashtags << hashtag
    end
  end

  before_update do
    idea = Idea.find_by(id: self.id)
    idea.hashtags.clear
    listhashtags.uniq.map do |ht|
      hashtag = Hashtag.find_or_create_by(name: ht.downcase.delete('#'))
      idea.hashtags << hashtag
    end
  end
  def idea_updated_at
    updated_at|| Time.new()
  end
  def self.generate_ideas(n = 5, user = nil)

    user ||= User.last
    n.times do
        a=''
        b = nil
        loop do
          b = Behance::Client.new(access_token: ENV.fetch('API_BEHANCE_KEY')).collections.first["latest_projects"].first["covers"]
          if b
            a = b["404"]
          end
          break if b !=nil
        end
        hashtag_idea = '#'+Faker::Job.field
        body_idea = ' '+ Faker::Hobbit.quote
        idea = Idea.create!(
        title: Faker::Cat.breed,
        body: hashtag_idea +  body_idea,
        need: Faker::Job.title,
        image_url: a,
        category_id: rand(1..5),
        type_id: rand(1..3),
        user: User.random_user,
      )
       rand(8).times do
         idea.comments.create(
           body: Faker::Hacker.say_something_smart,
           user: User.random_user,
         )
       end
       rand(30).times do
         idea.likes.create(
           user: User.random_user,
         )
       end
       rand(30).times do
         idea.participates.create(
           skills: "abc", details: "xyz", joiner: User.random_user
           )
       end
    end
  end

  def self.find_ideas_by_hashtag(hashtag)
    hashtag = Hashtag.find_by(name: hashtag)
    if hashtag!=nil
      return hashtag.ideas
    end
  end

  def image_url_or_photo
    if idea_attachments.first
      return idea_attachments.first.photo
    else
      image_url.presence||  "idea.jpg"
    end
  end
end

app/models/idea_attachment.rb
class IdeaAttachment < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :idea
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item, polymorphic: true
end

app/models/participate.rb
class Participate < ApplicationRecord
  belongs_to :joined_idea, class_name: 'Idea', foreign_key: "idea_id"
  # belongs_to :joined_idea, class_name: 'Idea', foreign_key: 'idea_id'
  belongs_to :joiner, class_name: 'User', foreign_key: "user_id"
  validates :skills,:details, presence: true
  validates_uniqueness_of :user_id, :scope => :idea_id
end

app/models/reach.rb
class Reach < ApplicationRecord
  belongs_to :user
  belongs_to :idea
  validates_uniqueness_of :user_id, :scope => :idea_id
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :ideas
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:facebook]
  has_many :ideas, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :follows, dependent: :destroy
  has_many :followers, through: :follows
  has_many :participates
  has_many :likes, dependent: :destroy
  # has_many :joined_ideas, through: :participates, source: 'idea'
  has_many :joined_ideas, through: :participates, source: 'joined_idea'
  has_many :reaches
  has_many :comments, dependent: :destroy
  mount_uploader :avatar, AvatarUploader
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image_url = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def image_url_or_default
    avatar.url|| image_url.presence || "idea.jpg"
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.generate_users(n = 5, gender = "female")
    url = "https://randomuser.me/api?results=#{n}&gender=#{gender}"
    body = HTTP.get(url).parse
    body["results"].each do |person|
      hash = {}
      hash[:name] = person["name"]["first"] + " " + person["name"]["last"]
      hash[:email] = person["email"]
      o = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
      string = (0...10).map { o[rand(o.length)] }.join
      hash[:password] = string
      hash[:image_url] = person["picture"]["large"]
      user = User.create! hash
    end


  end

  def self.num_followedby(user)
    Follow.where(follower: user).count
  end

  def self.num_ideas(user)
    user.ideas.count
  end

  def self.num_joined_ideas(user)
    user.joined_ideas.count
  end

  def is_followed?(user)
    followers.include?(user)
  end

  def name_or_email
    name || email
  end

  def liking?(item)
    likes.where(item: item).exists?
  end

  def reaching?(idea)
    reaches.where(idea: idea).exists?
  end


  def toggle_like!(item)
    if like = likes.where(item: item).first
      like.destroy
    else
      likes.where(item: item).create!
    end
  end

  def self.autocomplete(name)
    User.where("name ILIKE ? ", "%#{name}%")
  end
  def self.random_user
    User.offset(rand User.count).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(icon_name, text)
    content_tag(:span, fa_icon(icon_name), class: "icon") + content_tag(:span, text,class: "text-icon")
  end
  def flash_messages(opts = {})
    flash.map do |msg_type, message|
      content_tag(:div, class: "message #{class_for(msg_type)}") do
        content_tag(:div, class: "message-header") do
          (message + content_tag(:button, 'x'.html_safe, class: 'delete')).html_safe
        end
      end
    end.join.html_safe
  end

  def class_for flash_type
    { success: 'is-primary', error: 'is-danger', notice: 'is-warning'}[flash_type.to_sym]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
  def display_likers(idea)
    idea.likes.map{|like| like.name_or_email}.to_sentence
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reaches_helper.rb
module ReachesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommunityIdea</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.10&appId=1594152533929347";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.10&appId=1594152533929347";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <%= image_tag "idea.jpg", alt: "Idea community" %>
          </a>
          <div class="navbar-burger burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
        <div class="navbar-menu" id="navMenu">
          <div class="navbar-start">
            <div class="navbar-item has-dropdown is-hoverable">
              <%= link_to icon("lightbulb-o", "Ideas"), "" , class: "navbar-link is-active" %>
              <div class="navbar-dropdown ">
                <%= link_to "Popular", root_path(:sort_by => "popular") , class: "navbar-item #{'active' if params[:sort_by] == "popular"}"%>
                <%= link_to "Recent",root_path(:sort_by => "recent") , class: "navbar-item #{'active' if params[:sort_by] == "recent"}"%>
                <%= link_to "Follow", root_path(:sort_by => "follow") , class: "navbar-item #{'active' if params[:sort_by] == "follow"}"%>
                <%= link_to "Champion", root_path(:sort_by => "champion") , class: "navbar-item #{'active' if params[:sort_by] == "champion"}"%>
                <%= link_to icon("map-marker","Ho Chi Minh"), "" , class: "navbar-item"%>
                <%= link_to icon("tasks","Projects"), "" , class: "navbar-item"%>
              </div>
            </div>
          </div>
          <div class="navbar-end">
          <% if current_user %>
            <%= link_to "Sign out", destroy_user_session_path, class: "navbar-item", method: :delete %>
          <% else %>
            <%= link_to  "Sign up",new_user_registration_path, class: "navbar-item" %>
            <%= link_to "Sign in", new_user_session_path, class: "navbar-item" %>
          <% end %>
            <div class="navbar-item">
              <%= form_tag searchresult_path, :method => 'get' do  %>
                <div class="field">
                  <div class="control has-icons-right">
                    <%= text_field_tag :search, params[:search],placeholder: "Search...", class: "input ", id: "provider-remote", autocomplete: "off", style: "position: relative;"  %>
                    <span class="icon is-right is-small">
                      <%= fa_icon("search") %>
                    </span>
                  </div>
                  <div class="content-list" id="list" style="position: absolute;top: 50px;left: 0;">
                    <ul class="drop-list">
                      <li>
                        <a href="">
                          <span class="item">
                            <span class="icon people">
                              <span aria-hidden="true"><%= icon("users","")%></span>
                            </span>
                            <span class="text">People:</span>
                          </span>
                        </a>
                      </li>
                      <li>
                        <a href="">
                          <span class="item">
                            <span class="icon image">
                              <span  aria-hidden="true"><%= icon("tasks","")%></span>
                            </span>
                            <span class="text">Projects:</span>
                          </span>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
     <%= flash_messages %>
    <div style="color:black" >
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
  </body>
</html>